{{- if and .Values.ssdgate.installDex .Values.ssdgate.createGateDexSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: gate-dex-client-secret
type: Opaque
data:
  client-secret: {{  randAlphaNum 16| b64enc | quote }}
{{- end }}
