apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: gate
  name: ssd-gate
spec:
  ports:
  - name: ssd-gate
    port: 8084
    protocol: TCP
    targetPort: 8001
  selector:
    app: oes
    component: gate
  sessionAffinity: None
  type: ClusterIP
