apiVersion: v1
data:
  ssd-gate-config.yaml: |
{{- if eq .Values.global.oesUI.host "localhost" }}
    {{- tpl (.Files.Get "config/ssd-gate/config-local.yaml") . | nindent 4 }}
{{- else if eq .Values.ssdgate.auth_type "saml" }}
    {{- tpl (.Files.Get "config/ssd-gate/config-saml.yaml") . | nindent 4 }}
{{- else }}
    {{- tpl (.Files.Get "config/ssd-gate/config-dex.yaml") . | nindent 4 }}
{{- end }}
kind: ConfigMap
metadata:
  name: ssd-gate-config
  labels:
    app: ssd
    component: gate
{{ include "oes.standard-labels" . | indent 4 }}

