#####################################################
# This is a minimal configuration needed for SSD Installation
# Using builtin poc login
#####################################################

RabbitServiceType: LoadBalancer
UIServiceType: LoadBalancer

global:
  oesUI:
    protocol: http
    host: localhost
    port: 8080

noPvc: true
minio:
  mode: standalone
  persistence:
    enabled: false
ssdgate:
  installDex: false
  createGateDexSecret: false
  auth_type: poclogin
ui:
  serviceAnnotations:
    awsAnnotationsGo: HERE
rabbitmq:
  serviceAnnotations:
    awsAnnotationsGo: HERE
