rabbitmq:
  username: '{{ .Values.rabbitmq.username }}'
  password: '{{ .Values.rabbitmq.password }}'
  host: rabbitmq-service
  port: 5672
  queue: argo-ssd
  exchange: argo.events
  bindingKey: argo-ssd
  prefetchCount: 50

postgresql:
  ssddb:
    connectString: host=oes-db user='{{ .Values.db.username }}'  password='{{ .Values.db.password }}' database=ssddb port=5432
