apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ssd-role-{{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
