apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssd-role-rb-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ssd-role-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
