opsMxSvc: {{.Values.global.oesUI.protocol}}://{{.Values.global.oesUI.host}}
ssdOpa: http://ssd-opa:8200
graphqlsvc:
    host: http://dgraph-public
    port: 8080
postgresql:
    ssd:
      connectString: host=oes-db user='{{ .Values.db.username }}'  password='{{ .Values.db.password }}' database=ssddb
toolchain:
    host: http://tool-chain
    port: 8100
spinnaker:
    rabbitmq:
      username: '{{ .Values.rabbitmq.username }}'
      password: '{{ .Values.rabbitmq.password }}'
      host: rabbitmq-service
      port: 5672
      queue: preview-saas-ssd
      #queue: isd-to-preview-saas
      exchange: echo.events
      bindingKey: preview-saas-ssd
