#####################################################
# OpsMx AutoPilot and Integrated Spinnaker Delivery
# This file contains configurations for AP as well as Spinnaker
#####################################################

#This should not be required
#installationMode: SSD-SPIN

## Info related to registry where OES images are stored
imageCredentials:
  repoUrl: https://quay.io/
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: quay.io/opsmxpublic

#storageClass: standard
# noPvc is true, no PVCs will be created, suitable for minikube
noPvc: false

AESEncryptionKey: OKPQK0JWS2TVTW9E86IWWYN3VY4Z34WJ
####################################################
# kubernetes services can be exposed to a web-UI based 3 modes
# ClusterIP (will required Ingress or some other mechanism)
# or LoadBalancer or NodePort
# OES UI, OES Gate, Spinnaker Deck and Spinnaker Gate service type
k8sServiceType: ClusterIP
UIServiceType: ClusterIP
RabbitServiceType: LoadBalancer  # Type for the Rabbit MQ, default is LB, can be changed to ClusterIP

####################################################
# Global variables can be accessed across all the charts including sub-charts
global:
  # Custom Images registry where all the OSS and customized images used in the helm chart are stored
  # Only update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  customImages:
    registry: quay.io/opsmxpublic

  # when this flag is set to false; UI will be accessible over http instead of https
  # This does not appear to be used at all
  #ssl:
  #  enabled: false

  # If cert-manager is installed, TLS secrets will created automatically, as an 'Issuer' will be created
  # Else, the TLS secrets will need to created manually
  certManager:
    installed: false

  customCerts:
    enabled: false        # Set to true if your organization requires custom TLS certs
    secretName: oes-cacerts # Please do not change this

  ## Set to true to expose oes-ui, oes-gate services over ingress
  createIngress: false

  ## OES-UI url configuration, defaults to http://localhost:8080
  oesUI:
    protocol: http
    host: localhost
    # Use below port when hostname above is an external IP instead of a hostname
    #port: 8080

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: ssd-ui-ingress

  # Minio is needed for dGraph (till its need is removed)
  minio:
    enabled: true
    image:
      repository: quay.io/opsmxpublic/minio
      tag: RELEASE.2020-12-03T05-49-24Z  # RELEASE.2020-01-03T19-12-21Z
    mcImage:
      repository: quay.io/opsmxpublic/minio-mc
      tag: RELEASE.2020-11-25T23-04-07Z
    service:
      type: ClusterIP
    accessKey: spinnakeradmin
    secretKey: spinnakeradmin
    region: us-east-1
    #Below is the securityContext block for only for K8S
    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    buckets:
    - name: "spinnaker"
      policy: none
      purge: false
    - name: "autopilot"
      policy: none
      purge: false
    defaultBucket:
      enabled: true
      name: "spinnaker"
    nodeSelector: {}
    affinity: {}
    tolerations: []
    persistence:
      enabled: true
      size: 10Gi
dgraph:
  image:
    repository: dgraph
    tag: v23.1.0
ratel:
  image:
    repository: ratel
    tag: v21.12.0
curl:
  image:
    repository: curl
    tag: 8.6.0
customLabels:
  product: ssd
  vendor: opsmx
###############################################################################
ssdgate:
  image:
    repository: ssdgate
    tag: v1.0.1
  installDex: true
  createGateDexSecret: true
  #home_page: "/ui/index.html" # OPTIONAL default redirect page
  #session_timeout: 7200   # OPTIONAL login session timeout, it should match the authenticator timeout
  #skipstartcheck: true # OPTIONAL If true, pre-start checks will be skipped, well-known URL for OIDC cannot be used.
  #dex_url: "http://ssd-dex:5556" # OPTIONAL, Default is correct with OpsMx installed Dex

  auth_type: poclogin  # saml, dex_oidc and poclogin are other valid values
  admin_groups:
    - admin
  auth2_oidc:
    client_id: ssd-gate
    # kubectl create secret generic gate-dex-client-secret --from-literal client-secret=MYSECRET
    #client_secret: "encrypted:gate-dex-client-secret:client-secret" # Create a secret called gate-dex-client-secret with key client-secret
    entity_map:        # DEPENDS on the provider
      user_name: email #  Required for Dex
    #  roles: groups
    #well_known_url: http://my-well-known
    #redirect_url: "https//ssd-gate:8084/oidccallbackendpoint"       # OPTIONAL
    #userinfo_url: "https://dev-80355908.okta.com/oauth2/v1/userinfo"  # OPTIONAL
    # We need to "which field contains the username and roles"
    #endpoint:       # OPTIONAL Not required of well-known url is provided, else required
    #  auth_url: "https://dev-80355908.okta.com/oauth2/v1/authorize"
    #  token_url: "https://dev-80355908.okta.com/oauth2/v1/token"
    #scopes:         # OPTIONAL Not required of well-known url is provided, else required
    #  - openid      # openid MUST be specified, if used. 
    #  - offline_access # It is best to leave offline_access in
    #  - email
    #  - roles
  saml:
    metadata_url: https://dev-14704582.okta.com/app/exkdnjuo0wxJsOtua5d7/sso/saml/metadata
    saml_initiated_login: true
    #entity_id: http://test-ssd.ryzon7-isd40.opsmx.org
    #sign_request: false # DEPENDS Default is false, make it match the SAML setting
    ## Optional files, create saml-files secret as follows, "saml-files" secret name should not be changed
    ## k create secret generic saml-files --from-file metadata.xml --from-file certificate.crt --from-file private.key
    #metadata_File: /app/saml/metadata.xml  # OPTIONAL One of metadata url or file required, url preferred
    #session_crt_file: /app/saml/certificate.crt # OPTIONAL
    #session_key_file: /app/saml/private.key #  OPTIONAL
    #entity_map: # OPTIONAL
    #  user_name: email  # Default is to take from the "subject" of the assertion. Use this to get it from an attribute
    #  roles: groups  # groups is default

###############################################################################
db:
  ## Set it to false if any external database is to be used
  enabled: true

  ## Change the default configuration when above option is set to false
  ## Below url and credentials are used by Autopilot & Sapor
  url: jdbc:postgresql://oes-db:5432
  username: postgres
  password: networks123

  ## Image specific details
  image:
    repository: ubi8-oes-db
    tag: v3.0.0-ssd
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

  ## Strategy to rollout statefulset pods
  podManagementPolicy: OrderedReady

  ## Default group to which the default user of a pod belongs and it applies only to K8S
  securityContext:
    fsGroup: 1000

  ## storageMountSize is the size with which a PVC is to be created
  storageMountSize: 8Gi

####################################################
toolchain:
  ## Image specific details
  image:
    repository: tool-chain
    tag: v4.0.4-rc4
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

####################################################
supplychainpreprocessor:
  ## Image specific details
  image:
    repository: supplychain-preprocessor
    tag: v4.0.4-rc4
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}
  
####################################################
ssdopa:
  ## Image specific details
  image:
    repository: ssd-opa
    tag: v4.0.4-rc4
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  persistence:
    size: 5Gi
    accessMode: ReadWriteOnce

####################################################
supplychainapi:
  ## Image specific details
  image:
    repository: supplychain-api
    tag: v4.0.4-rc4
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

###############################################################################
## Details of rabbitmq message bus image for OES
##
rabbitmq:
  ## rabbitmq  endpoint that is used by oes-gate and oes-platform for caching;
  ## Change this to custom URL if installRedis is set to false
  url: rabbitmq-service
  port: 5672
  username: rabbitmq
  password: Networks123
  image:
    registry: quay.io/opsmxpublic/rabbitmq
    repository: 3-management

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

  #Below block is for only for K8S
  securityContext:
    fsGroup: 1000
    
###############################################################################
## Values of OES UI
ui:
  ## Image specific details
  image:
    repository: ubi8-oes-ui
    tag: v4.0.4-rc7
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: "isd"

  serviceAnnotations: {}

  config:
    ## Interval, in millsecs, at which UI refreshes application dashboard
    setApplicationRefreshInterval: 300000

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
dex:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []
minio:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []

###############################################################################################
#### The values below this line are best not changed except in rare situations
###############################################################################################
# Leave it as true, even if not using OPA
opa:
  enabled: true
  image:
    repository: opa
    tag: v0.47.0
    pullPolicy: IfNotPresent
  annotations:
    moniker.spinnaker.io/application: isd

dex:
  configSecret:
    create: false
    name: "gate-dex-config"
  volumes:
    - name: gate-dex-client-secret
      secret:
        defaultMode: 420
        secretName: gate-dex-client-secret
  env:
    - name: GATE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: gate-dex-client-secret
          key: client-secret
