apiVersion: v1
data:
  ssd-integrations.yaml: |
    {{- tpl (.Files.Get "config/oes-supplychain-api/ssd-integrations.yaml") . | nindent 4 }}
kind: ConfigMap
metadata:
  name: supplychain-api-cm
  labels:
    app: ssd
    component: oes-supplychain-api
{{ include "oes.standard-labels" . | indent 4 }}

