{{- if not .Values.noPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tool-chain
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.storageClass }}
{{- if (eq "-" .Values.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storageClass }}"
{{- end }}
{{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
{{- end }}
