apiVersion: v1
kind: ConfigMap
metadata:
  name: tool-chain
  labels:
    app: oes
{{ include "oes.standard-labels" . | indent 4 }}
    component: oes-toolchain
data:
{{ (tpl (.Files.Glob "config/oes-toolchain/tool-chain.yaml").AsConfig . ) | indent 2 }}
