ssd_baseurl: {{.Values.global.oesUI.protocol}}://{{.Values.global.oesUI.host}}

{{- if .Values.ssdgate.home_page }}
home_page: {{.Values.ssdgate.home_page }}
{{- end }}
{{- if .Values.ssdgate.session_timeout }}
session_timeout: {{.Values.ssdgate.session_timeout }}
{{- end }}
{{- if .Values.ssdgate.skipstartcheck }}
skipstartcheck: {{.Values.ssdgate.skipstartcheck }}
{{- end }}
{{- if .Values.ssdgate.dex_url }}
dex_url: {{.Values.ssdgate.dex_url }}
{{- end }}
auth_type: {{.Values.ssdgate.auth_type}}
admin_groups:
{{- toYaml .Values.ssdgate.admin_groups |nindent 0 }}

{{- if eq .Values.ssdgate.auth_type "dex_oidc"}}
auth2_oidc:
  {{- if .Values.ssdgate.auth2_oidc.client_id }}
  client_id: {{.Values.ssdgate.auth2_oidc.client_id }}
  {{- else }}
  client_id: ssd-gate
  {{- end }}
  client_secret: "encrypted:gate-dex-client-secret:client-secret"
  {{- if .Values.ssdgate.auth2_oidc.well_known_url }}
  well_known_url: "{{.Values.ssdgate.auth2_oidc.well_known_url}}"
  {{- else }}
  well_known_url: "{{.Values.global.oesUI.protocol}}://{{.Values.global.oesUI.host}}/dex/.well-known/openid-configuration"
  {{- end }}
  {{- if .Values.ssdgate.auth2_oidc.userinfo_url }}
  userinfo_url: "{{.Values.ssdgate.auth2_oidc.userinfo_url }}
  {{- end }}
  {{- with .Values.ssdgate.auth2_oidc.endpoint }}
  endpoint:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ssdgate.auth2_oidc.entity_map }}
  entity_map:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ssdgate.auth2_oidc.scopes }}
  scopes:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
