# Backend services to route the calls to. Routes are processed in the order provided here
# All routed configured can be viewed in the browser at the /showroutes endpoint
# The 3 routes below are optional, they are filled in automatically if nothing is specified
# services:   # OPTIONAL default backends are programmed in. If specified ALL backends including these MUST be included
- name: supplychain-api-unauth   # Unauthenticated end-point for web-hook posts, we could add JWT to make it authenticated
  path_prefixes:
  - "/ssdservice/v1/spinnakerevents"
  baseUrl: supplychain-api:8099
  health_endpoint: /health
  log_traffic: true
- name: ssd-opa-unauth   # Unauthenticated end-point for web-hook posts, we could add JWT to make it authenticated
  path_prefixes:
  - "/webhook/api/v1/dataCollection" 
  - "/webhook/api/v1/bundle.tar.gz"
  - "/webhook/logs/api/v1/deploymentFirewallDecisionLogs"
  - "/webhook/api/v1/opaPermission"
  strip_path: "/webhook"  # Remove /webhook before sending to ssd-opa
  baseUrl: ssd-opa:8200
  health_endpoint: /health
  log_traffic: true
- name: supplychain-api  # Name
  path_prefixes:
  - "/ssdservice"        # incoming calls are routed based on this. Processed in Order i.e. we can have multiple of these going to the same backend
  baseUrl: supplychain-api:8099
  #disabled: false          # Default false, set this to true to temporarily disable a service
  #scheme: http           # Default http. If the Backend is httpS, please set it
  #streaming: false # Default is false. set this if we have a streaming backend e.g. a service that returns results of a DB-query
  auth_required: true # Default false. Note that if the backend does not need auth i.e it will not get the user who requested this
  #strip_prefix: false  # Default false. If true, the path_prefix is removed before sending to backend. Best is to use only ONE path_prefix
  #health_endpoint: /healthz # Default, change only if required
  log_traffic: true
- name: rabbitmq
  path_prefixes:
  - "/rabbit"
  baseUrl: rabbitmq-service:15672
  health_endpoint: /
  strip_prefix: true
- name: ssd-opa
  path_prefixes:
  - "/ssd-opa"
  baseUrl: ssd-opa:8200
  health_endpoint: /health
  strip_prefix: true
  log_traffic: true
  auth_required: true
- name: supplychain-preprocessor
  baseUrl: supplychain-preprocessor:8058
  health_endpoint: /healthz
  auth_required: true
- name: tool-chain
  baseUrl: tool-chain:8100
  health_endpoint: /health
  auth_required: true
- name: dgraph
  baseUrl: dgraph-public:8000
  health_endpoint: /
  auth_required: true
- name: oes-ui
  baseUrl: oes-ui:8080
  health_endpoint: "/ui/index.html"
  auth_required: true
- name: ssd-minio 
  baseUrl: ssd-minio:9000
  health_endpoint: ""
  auth_required: true
{{- if .Values.ssdgate.installDex }}
- name: ssd-dex
  baseUrl: ssd-dex:5558
  health_endpoint: /healthz/ready
{{- end }}
