
ssd_baseurl: http://localhost:8080

#auth_type: "poclogin"  # Defaulting so Dex config is not required
auth_type: "dex_oidc"  # This is need to tell the "type" of authentication
auth2_oidc:
  client_id: ssd-gate
  client_secret: iKJX6nreyoQbtdNs
  #client_secret: "encrypted:gate-dex-client-secret:client-secret"
  #well_known_url: "http://localhost:8080/dex/.well-known/openid-configuration"
  userinfo_url: "http://ssd-dex:5556/dex/userinfo"
  endpoint:
    auth_url:  "http://localhost:8080/dex/auth"
    token_url: "http://ssd-dex:5556/dex/token"
  entity_map:
    user_name: email
  scopes:
    - openid
    - offline_access
